---
title: "Home"
---

# About Me

Hi, I’m Ash. I’m a junior double majoring in Philosophy and Mathematics-Computer Science with a specialization in Data Science. I’m especially interested in the philosophy of mind and the ways data science and philosophy intersect—particularly when it comes to understanding human behavior and decision-making. Data science lets me explore real-world problems, while my background in philosophy helps me think critically about the implications of what I find.

When I’m not working on school stuff, you can find me playing indie games like Stardew Valley or Moonstone Island. I’m a fan of all sorts of music, from jazz to hyperpop to rock. I also love cozy things—hot chocolate, blankets, and fall are some of my favorite comforts. If I’m not gaming or listening to music, I’ll probably be baking cupcakes (they’re easier to share) for my friends or catching up on Severance (no spoilers, please).

------------------------------------------------------------------------

You can find my GitHub [here](https://github.com/ashleymikali).
