project:
  type: website

website:
  title: "Ashley Russell | Portfolio"
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      #- section: "About "
        #href: about.qmd
      - section: "Projects"
        contents:
        - analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2