name: Sync Projects from Other Repositories

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Portfolio Repository
        uses: actions/checkout@v3
        with:
          repository: ashleymikali/ashleymikali.github.io
          
      - name: Checkout Spending Habits Project Repository
        uses: actions/checkout@v3
        with:
          repository: ashleymikali/spending-habit-prediction
          path: projects/spending-habit-prediction
          
      - name: List Files in Project Repository
        run: ls -R
        
      - name: Set up GitHub Token
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PORTFOLIO_TOKEN }}@github.com/ashleymikali/ashleymikali.github.io.git
        
      - name: Create target directory for Spending Habits Project in Portfolio
        run: |
          mkdir -p ./projects/spending-habit-prediction
          
      - name: Remove any .git directories in source
        run: find spending-habit-prediction/ -name ".git" -type d -exec rm -rf {} +


      - name: Copy analysis.qmd and Data Folder to Portfolio Repository
        run: |
          cp spending-habit-prediction/spending-habit-prediction/analysis.qmd ./projects/spending-habit-prediction/
          cp -r spending-habit-prediction/spending-habit-prediction/data ./projects/spending-habit-prediction/

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Sync Spending Habits Project files"
          git push origin main