name: Sync Projects from Other Repositories

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Portfolio Repository
        uses: actions/checkout@v3
        with:
          repository: ashleymikali/ashleymikali.github.io
          
      - name: Checkout Spending Habits Project Repository
        uses: actions/checkout@v3
        with:
          repository: ashleymikali/spending-habit-prediction
          path: spending-habit-prediction

      - name: Copy analysis.qmd and Data Folder to Portfolio Repository
        run: |
          cp spending-habit-prediction/analysis.qmd ./projects/spending-habit-prediction/
          cp -r spending0habit-prediction/data ./projects/spending-habit-prediction/
          
      - name: Commit and Push Changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Sync Spending Habits Project files to Portfolio" || echo "No changes to commit"
          git push origin main